export const FETCH_PRODUCTS = "FETCHPRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCHPRODUCTSSUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCHPRODUCTSFAILURE";
export const GET_PRODUCTS_CATEGORIES = "GETPRODUCTSCATEGORIES";
export const GET_FILTERED_PRODUCTS = "GETFILTEREDPRODUCTS";
export const CART_PRODUCTS = "CARTPRODUCTS";
export const CART_PRODUCTS_PRICE = "CARTPRODUCTSPRICE";

